#!/bin/bash
# The local dev instance's setup (FN-10, step 3b), run by the root project's `setup` at every
# environment start, so a fresh or reset environment has the dev instance without hand work.
#
# It writes the repo root's `.env`, which honcho and `flask run` read (so `scripts/dev.py` picks
# it up), and seeds the dev instance's store: a scratch copy of the Fieldnotes store under
# backend/.run/dev, so rulings made here never reach the real one. The `.env` is rewritten every
# time; the scratch store is seeded only when it is missing, so what was ruled on it survives a
# restart. Refresh it (stack stopped): rm -rf backend/.run/dev and run this again.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEV="$ROOT/backend/.run/dev"
STORE_SOURCE=/work/Fieldnotes # the store's checkout, a repo of this environment

if [[ ! -d "$DEV/remote.git" ]]; then
    if [[ ! -d "$STORE_SOURCE/.git" ]]; then
        echo "no store checkout at $STORE_SOURCE: the dev instance has no store" >&2
        exit 1
    fi
    rm -rf "$DEV/checkout" # a checkout of an earlier scratch store would not match this one
    mkdir -p "$DEV"
    git init --quiet --bare --initial-branch main "$DEV/remote.git"
    # The checkout's view of the store's main, remote-tracking branch first: its local main may lag.
    ref=origin/main
    git -C "$STORE_SOURCE" rev-parse --verify --quiet "$ref" >/dev/null || ref=main
    git -C "$STORE_SOURCE" push --quiet "$DEV/remote.git" "$ref:refs/heads/main"
    echo "seeded the dev instance's store from $STORE_SOURCE ($ref)"
fi

cat >"$ROOT/.env" <<EOF
# Generated by scripts/dev-instance-setup.sh at every environment start: edit that, not this.
# The local dev instance (FN-10, step 3b), started with scripts/dev.py. The store is a scratch
# copy, so rulings made here never reach the real one.
BASEURL=https://fieldnotes.${KUBECODER_ENVIRONMENT_ID:?not set: this runs in a KubeCoder environment}.home
OIDC_ENABLED=false
FIELDNOTES_STORE_URL=$DEV/remote.git
FIELDNOTES_STORE_DIR=$DEV/checkout
FIELDNOTES_CACHE_DIR=$DEV/cache
# No FIELDNOTES_KUBECODER_*: a submit here starts no actioner.
EOF
