"""Pydantic wire models of the Fieldnotes REST surface, shared by the API and the MCP server."""

from __future__ import annotations

from .api import (
    AREA_MAX,
    EMOJI_MAX,
    MAX_CANDIDATES,
    POST_CANDIDATES,
    REPO_MAX,
    SESSION_MAX,
    TEXT_MAX,
    AreaText,
    BoardSyncReply,
    BodyText,
    Candidate,
    EmojiText,
    HealthReply,
    HookReply,
    MatchClass,
    MatchReply,
    MatchRequest,
    NeighborsReply,
    PostReply,
    PostRequest,
    ReactReply,
    ReactRequest,
    RepoText,
    SessionText,
)
from .observation import (
    ID_PATTERN,
    POST_EMOJI,
    Category,
    Comment,
    Observation,
    Outcome,
    Reaction,
    Status,
)
from .problem import Problem, ProblemType

__all__ = [
    # api
    "AREA_MAX",
    "EMOJI_MAX",
    "MAX_CANDIDATES",
    "POST_CANDIDATES",
    "REPO_MAX",
    "SESSION_MAX",
    "TEXT_MAX",
    "AreaText",
    "BoardSyncReply",
    "BodyText",
    "Candidate",
    "EmojiText",
    "HealthReply",
    "HookReply",
    "MatchClass",
    "MatchReply",
    "MatchRequest",
    "NeighborsReply",
    "PostReply",
    "PostRequest",
    "ReactReply",
    "ReactRequest",
    "RepoText",
    "SessionText",
    # observation
    "ID_PATTERN",
    "POST_EMOJI",
    "Category",
    "Comment",
    "Observation",
    "Outcome",
    "Reaction",
    "Status",
    # problem
    "Problem",
    "ProblemType",
]
